name: dev_panel_control
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
# هنا نقوم بتحديث رقم الاصدار يكفي +3
version: 1.0.0+2

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins: 
    sdk: flutter   



  cupertino_icons: ^1.0.6
  firebase_core: ^2.30.1
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.19.4
  firebase_storage: ^11.7.4
  provider: ^6.1.2
  image_picker: ^1.1.2
  flutter_localizations:
    sdk: flutter
  intl: any
  intl_utils: ^2.8.7
  intl_translation: ^0.20.0
  shared_preferences: ^2.2.3
  cached_network_image: ^3.3.1
  double_back_to_close_app: ^2.1.0
  sqflite: ^2.3.3+1
  pdf: ^3.11.0
  printing: ^5.13.1
  qr_flutter: ^4.1.0
  flutter_launcher_icons: ^0.13.1
  file_picker: ^8.0.5
  url_launcher: ^6.3.0
  go_router: ^14.2.0
  permission_handler: ^11.3.1
  qr_code_scanner: ^1.0.0
  just_audio: ^0.9.39
  path: any
  fluttertoast: ^8.2.8
  country_state_city_pro: ^0.0.6
  http: ^1.2.2
  share_plus: ^10.0.0
  flutter_image_compress: ^2.3.0
  flutter_typeahead: ^5.2.0
  syncfusion_flutter_xlsio: ^27.1.53

dev_dependencies:
  flutter_test:
    sdk: flutter



  flutter_lints: ^3.0.0


flutter_icons:
  image_path: "assets/img/logo.png"
  android: true
  ios: true
  web:
    image_path: "assets/img/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true # Add this line

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - assets/img/
    - assets/store/
    - assets/sliders/
    - assets/sound/
  fonts:
    - family: Beiruti
      fonts:
        - asset: assets/fonts/Beiruti.ttf
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal-Black.ttf
          weight: 900
        - asset: assets/fonts/Tajawal/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Tajawal/Tajawal-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Tajawal/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/Tajawal/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal/Tajawal-Regular.ttf
          weight: 400

  
flutter_intl:
  enabled: true


